#!/usr/bin/env bash
# ------------------------------------------------------------
# run_gemma3_visual_test.sh
#
# This script calls gemma3_visual_test.py and passes the necessary command-line arguments.
# Usage:
#   bash run_gemma3_visual_test.sh
# ------------------------------------------------------------

# —— Configuration —— 
# Replace the following paths with your actual locations:

# Path to the CSV file containing Goal/Target pairs
INSTRUCT_PAIRS="/gpfs-flash/hulab/zhangwei_srt/lige/princeton/harmful_corpus/JBB-harmful-behaviors.csv"

# Path to the adversarial image (adv_best_noise.png) generated by APGD
ADV_IMG_PATH="/gpfs-flash/hulab/zhangwei_srt/lige/princeton/gemma3-4b-unconstrained/adv_iter_2000.png"

# Path to the Gemma3 checkpoint directory
MODEL_CKPT="/gpfs-flash/hulab/zhangwei_srt/lige/weights/gemma-3-4b-it"

# Device to run on (e.g., cuda:0, cuda:7, or cpu)
DEVICE="cuda:7"

# Random seed (optional; default in script is 17)
SEED=17

# Python interpreter to use (absolute path if needed)
PYTHON_BIN="/gpfs-flash/hulab/zhangwei_srt/miniconda3/envs/minigpt4/bin/python"

# —— Invocation —— 

$PYTHON_BIN gemma3_visual_test.py \
  --seed $SEED \
  --instruct_pairs "$INSTRUCT_PAIRS" \
  --adv_img_path "$ADV_IMG_PATH" \
  --model_ckpt "$MODEL_CKPT" \
  --device "$DEVICE"